#!/bin/bash

#Move dlmc data folder to the same directory as this 'SDDMM' directory such that
# it has relative path ../dlmc

DATE=$(date +'%m%d%Y')
HOST=$(hostname)
OUTPUT_FILE="summary-perf-sddmm-1550-fromfile_v4_${DATE}_${HOST}.txt"
CPPFILE=sddmm-esimd-fromfile_v4.cpp
EXECUTABLE=sddmm-fromfile_v4
CSV_FILE_NOQUOTES="sddmm-fromfile_v4_${DATE}_${HOST}.csv"
CSV_FILE=\"${CSV_FILE_NOQUOTES}\"

rm -f ${OUTPUT_FILE} ${CSV_FILE_NOQUOTES}

declare -A batch_sizes

fileName="../dlmc/rn50_batchsizes_noconv.txt"

OIFS=$IFS
IFS=','
while read key value
do
    batch_sizes+=( ["$key"]="$value" )
done < $fileName
IFS=$OIFS

#compile the code
icpx -std=c++20 -DOUTPUT_CSV_FILE=$CSV_FILE -fsycl -fsycl-targets=spir64_gen -Xsycl-target-backend "-device pvc" -o ${EXECUTABLE} $CPPFILE


for workload in $(find ../dlmc/rn50 -name "*.smtx")
do
 #   if [ "${workload}" == "../dlmc/rn50/magnitude_pruning/0.5/bottleneck_2_block_group_projection_block_group4.smtx" ]; then
        file_name=$(basename $workload)
        echo $workload
        batch_size=${batch_sizes["${file_name%.*}"]}
        if [ -z "$batch_size" ]; then
            continue
        fi

        echo $batch_size

        
        CE_SCOPE_EVENTS=0 ZE_AFFINITY_MASK=0 EnableImplicitScaling=0 ONEAPI_DEVICE_SELECTOR=level_zero:gpu ./${EXECUTABLE} $workload $batch_size >> $OUTPUT_FILE
#    fi
done
